### ISSUE TITLE
Unable to connect to Salesforce

### ISSUE THREAD

**Issue by daniel-blopez** [eroispaziali/ForceFlow#3] opened 2016-09-26 20:48 UTC
Not sure if this is related to the ForceFlow tool but I keep getting "Unable to connect to Salesforce" when executing the ant deployment script.

My build.xml is the following

``` xml
<project name="Test" default="deployCode" basedir="." xmlns:sf="antlib:com.salesforce" xmlns:forceflow="antlib:com.spaceheroes">
    <!-- Properties -->
    <property file="${basedir}/build.properties"/>
    <property environment="env"/>

    <!-- Import the Force Migration Tool and ForceFlow.
    This assumes all jars are in a folder named "lib" -->
    <path id="ant.additions.classpath">
        <fileset dir="${basedir}/lib/" includes="*.jar"/>
    </path>
    <taskdef resource="com/salesforce/antlib.xml" uri="antlib:com.salesforce" classpathref="ant.additions.classpath" />
    <taskdef resource="com/spaceheroes/task/antlib.xml" uri="antlib:com.spaceheroes" classpathref="ant.additions.classpath" />

    <target name="deployLocal">
        <sf:deploy username="${sf.username}" password="${sf.password}" serverurl="${sf.serverurl}" deployRoot="src">
        </sf:deploy>

        <!-- Execute needed Apex code -->
        <!-- NOTE: This requires ForceFlow, see lib directory for details -->
        <forceflow:apex
            username="${sf.username}"
            password="${sf.password}"
            serverurl="${sf.serverurl}">
            <![CDATA[
                System.debug('Hello from the ant deployment script!');
            ]]>
        </forceflow:apex>
    </target>

</project>
```

The first task, which is sf:deploy is working fine, it's using the same credentials as in the forceflow:apex.

Do you have any idea n why is this happening?

Thank you
Daniel

P.S. ForceFlow is awesome!

**Comment by eroispaziali** [comment] 2016-09-26 20:50
Hey can you post the output of your script too?

**Comment by daniel-blopez** [comment] 2016-09-26 20:53
Output is the following:

```
Buildfile: /Users/daniel.lopez/Projects/Workspace/SFDLopez/build.xml

deployLocal:
[sf:deploy] Request for a deploy submitted successfully.
[sf:deploy] Request ID for the current deploy task: 0Af4100000FDruMCAT
[sf:deploy] Waiting for server to finish processing the request...
[sf:deploy] Request Status: Pending
[sf:deploy] Request Status: InProgress (208/527)  -- Processing Type: ApexComponent
[sf:deploy] Request Status: InProgress (251/527)  -- Processing Type: ApexPage
[sf:deploy] Request Status: InProgress (421/527)  -- Processing Type: ApexClass
[sf:deploy] Request Status: InProgress (514/527)  -- Processing Type: Profile
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: Succeeded
[sf:deploy] *********** DEPLOYMENT SUCCEEDED ***********
[sf:deploy] Finished request 0Af4100000FDruMCAT successfully.

BUILD FAILED
/Users/daniel.lopez/Projects/Workspace/LobDev_Portal5x_DLopez/build.xml:34: Unable to connect to Salesforce

Total time: 1 minute 24 seconds
```

**Comment by eroispaziali** [comment] 2016-09-26 20:56
Okay, that helps. Do you know what API version of the Migration tool you are using? My guess is that forceflow is using an older version of the API and this messes up establishing the connection.

**Comment by daniel-blopez** [comment] 2016-09-26 20:57
Yes, I'm using version 36. I think this might have something to do with the newer TLS changes SF made recently but not sure.

**Comment by eroispaziali** [comment] 2016-09-26 21:40
Hey I just created [a new release](https://github.com/eroispaziali/ForceFlow/releases/tag/0.0.9) that upgrades to API 37. I tested the `executeApex` task, it works like a charm. This should solve the issue. Update your folder with the new JAR (pick the one with dependencies).  That should do.

**Comment by daniel-blopez** [comment] 2016-09-27 13:37
Hey man, thank you for your time.

I tried it with the new version but now I'm getting:

# 

```
Buildfile: /Users/daniel.lopez/Projects/Workspace/LobDev_Portal5x_DLopez/build.xml
  [taskdef] Could not load definitions from resource com/spaceheroes/task/antlib.xml. It could not be found.

deployLocal:
[sf:deploy] Request for a deploy submitted successfully.
[sf:deploy] Request ID for the current deploy task: 0Af4100000FkcoICAR
[sf:deploy] Waiting for server to finish processing the request...
[sf:deploy] Request Status: Pending
[sf:deploy] Request Status: InProgress (208/527)  -- Processing Type: ApexComponent
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress (257/527)  -- Processing Type: CustomObject
[sf:deploy] Request Status: InProgress (421/527)  -- Processing Type: ApexClass
[sf:deploy] Request Status: InProgress (421/527)  -- Processing Type: ApexClass
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: Succeeded
[sf:deploy] *********** DEPLOYMENT SUCCEEDED ***********
[sf:deploy] Finished request 0Af4100000FkcoICAR successfully.

BUILD FAILED
/Users/daniel.lopez/Projects/Workspace/LobDev_Portal5x_DLopez/build.xml:34: Problem: failed to create task or type antlib:com.spaceheroes:apex
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration. 
Action: Check that the implementing library exists in one of:
        -/usr/local/Cellar/ant/1.9.7/libexec/lib
        -/Users/daniel.lopez/.ant/lib
        -a directory added on the command line with the -lib argument

Total time: 1 minute 45 seconds
```

# 

If you can notice in the output above, when the script is just called it says:
[taskdef] Could not load definitions from resource com/spaceheroes/task/antlib.xml. It could not be found.

I tried to package it myself using maven and the sources but I get the same error.

**Comment by daniel-blopez** [comment] 2016-09-27 19:02
I repacked the jar file with the antlib.xml from the source code.

Now it's running again but now I get the Unable to connect to Salesforce error back:

# 

```
Buildfile: /Users/daniel.lopez/Projects/Workspace/LobDev_Portal5x_DLopez/build.xml

deployLocal:
...
...
[sf:deploy] *********** DEPLOYMENT SUCCEEDED ***********
[sf:deploy] Finished request 0Af4100000FlYJACA3 successfully.

BUILD FAILED
/Users/daniel.lopez/Projects/Workspace/LobDev_Portal5x_DLopez/build.xml:34: Unable to connect to Salesforce

Total time: 1 minute 56 seconds
```

# 

Do I need to do something else to make it work? You said it was working fine for you, perhaps I'm missing something.

Thank you in advance!

**Comment by eroispaziali** [comment] 2016-09-27 19:26
Hi I think it would help if you could share the full build.xml file you are
using. Remove all passwords, but leave everything else as it is!

**Comment by daniel-blopez** [comment] 2016-09-27 19:49
Here are my build.xml and build.properties:

## build.xml:

``` xml
<project name="Customer Portal" default="deployCode" basedir="." xmlns:sf="antlib:com.salesforce" xmlns:forceflow="antlib:com.spaceheroes">
    <!-- Properties -->
    <property file="${basedir}/build.properties"/>
    <property environment="env"/>

    <!-- Import the Force Migration Tool and ForceFlow.
    This assumes all jars are in a folder named "lib" -->
    <path id="ant.additions.classpath">
        <fileset dir="${basedir}/lib/" includes="*.jar"/>
    </path>
    <taskdef resource="com/salesforce/antlib.xml" uri="antlib:com.salesforce" classpathref="ant.additions.classpath" />
    <taskdef resource="com/spaceheroes/task/antlib.xml" uri="antlib:com.spaceheroes" classpathref="ant.additions.classpath" />

    <target name="deployLocal">
        <sf:deploy username="${sf.username}" password="${sf.password}" serverurl="${sf.serverurl}" deployRoot="src">
        </sf:deploy>

        <!-- Execute needed Apex code (I.e. Banking Services Data Provider ) -->
        <!-- NOTE: This requires ForceFlow, see lib directory for details -->
        <forceflow:apex
            username="${sf.username}"
            password="${sf.password}"
            serverurl="${sf.serverurl}">
            <![CDATA[
                nForce.LifeCycleDao dao = new nForce.LifeCycleDao(provider);
                dao.performAllDml();
            ]]>
        </forceflow:apex>
    </target>

</project>
```

## build.properties

```
# build.properties
#
# Do not commit changes to this file to the repo.
#
# Specify the login credentials for the desired Salesforce organization
sf.username = daniel.lopez@lob.dev
sf.password = ThisIsASecret
#sf.sessionId = <Insert your Salesforce session id here.  Use this or username/password above.  Cannot use both>
#sf.pkgName = <Insert comma separated package names to be retrieved>
#sf.zipFile = <Insert path of the zipfile to be retrieved>
#sf.metadataType = <Insert metadata type name for which listMetadata or bulkRetrieve operations are to be performed>

# Use 'https://login.salesforce.com' for production or developer edition (the default if not specified).
# Use 'https://test.salesforce.com for sandbox.
sf.serverurl = https://login.salesforce.com

sf.maxPoll = 20
```

I hope this helps.

Aren't you receiving the error for the missing resource com/spaceheroes/task/antlib.xml?

Thank you once again

**Comment by daniel-blopez** [comment] 2016-10-05 18:28
@eroispaziali Did you have the chance to check this one yet?

Thank you,
Daniel

**Comment by eroispaziali** [comment] 2016-10-06 17:01
@daniel1404 hey! I couldn't replicate the issue and it's hard for me to go further. I suggest to make sure you update your libraries with the latest release of ForceFlow AND the latest force migration tool (download it fresh from your org) and make sure you have no other JAR that might create resolution conflicts.

**Comment by frmarcio** [comment] 2016-10-24 16:48
The issue is when takes the serverURL as test.salesforce.com the project does not take correctly the serverURL when passing by parameter.

**Comment by eroispaziali** [comment] 2016-10-25 07:25
Thanks, will investigate!

**Comment by eroispaziali** [comment] 2016-10-25 21:08
@daniel1404 @frmarcio hey guys, I have good news! I finally managed to reproduce and solve the issue. [A new release that solves the issue is up](https://github.com/eroispaziali/ForceFlow/releases/tag/0.0.10), please update your jars, try again and let me know!

**Comment by daniel-blopez** [comment] 2016-10-25 21:12
Thank you @eroispaziali, I will try again with the updated jars and let you know as soon as I have results.

**Comment by eroispaziali** [comment] 2016-10-25 21:24
@daniel1404 fantastic. One last thing. Double check your `taskdef`lines in your build.xml, looks like your not specifying the path correctly.

It should be like this
`<taskdef resource="antlib.xml" uri="antlib:com.spaceheroes" classpathref="ant.additions.classpath" />` 

The attribute resource must be antlib.xml, yours looks like it has a different path.

**Comment by eroispaziali** [comment] 2016-10-26 07:41
Fix released in 0.0.10

**Closed as completed by eroispaziali** 2016-10-26 07:41 UTC

**Comment by frmarcio** [comment] 2016-11-23 11:53
Worked very well for me since I have installed 0.0.10 version!

Many thanks !

**Comment by SreelakshmiSomalraju** [comment] 2017-02-13 12:26
Hi,

I am getting Unable to connect salesforce issue after I followed all the above steps. Could you please help me to resolve this issue.

FYI, I have downloaded both .jar files forceflow and forceflow dependencies of 0.0.10 version.

Need help to configure the source code.zip file if required.
